
"use client";

import { useMemo } from 'react';
import {
  Bar,
  BarChart,
  ResponsiveContainer,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
} from "recharts";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import type { Transaction, User } from '@/lib/types';

interface EmployeeSalesChartProps {
  data: Transaction[];
  users: User[];
  isLoading?: boolean;
}

export function EmployeeSalesChart({ data, users, isLoading }: EmployeeSalesChartProps) {
  const employeeSalesData = useMemo(() => {
    if (!data || !users) return [];
    
    const salesByEmployee = data.reduce((acc, transaction) => {
      const userId = transaction.userId;
      acc[userId] = (acc[userId] || 0) + transaction.subtotal;
      return acc;
    }, {} as Record<number, number>);

    return Object.entries(salesByEmployee)
      .map(([userId, totalSales]) => {
        const user = users.find(u => u.id === Number(userId));
        return {
          name: user ? user.name.split(' ')[0] : 'Unknown', // Use first name for brevity
          total: totalSales,
        };
      })
      .sort((a, b) => b.total - a.total);

  }, [data, users]);

  return (
    <Card>
      <CardHeader>
        <CardTitle>Sales by Employee</CardTitle>
        <CardDescription>
          Total revenue generated by each employee.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <Skeleton className="h-[300px] w-full" />
        ) : (
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={employeeSalesData} margin={{ top: 5, right: 20, left: -10, bottom: 5 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis
                dataKey="name"
                stroke="hsl(var(--muted-foreground))"
                fontSize={12}
                tickLine={false}
                axisLine={false}
              />
              <YAxis
                stroke="hsl(var(--muted-foreground))"
                fontSize={12}
                tickLine={false}
                axisLine={false}
                tickFormatter={(value) => `Ksh ${value / 1000}k`}
              />
              <Tooltip
                cursor={{ fill: 'hsl(var(--muted))' }}
                contentStyle={{ 
                  backgroundColor: 'hsl(var(--background))',
                  borderColor: 'hsl(var(--border))',
                  borderRadius: 'var(--radius)',
                }}
                labelStyle={{ color: 'hsl(var(--foreground))' }}
                formatter={(value: number) => [new Intl.NumberFormat("en-US", { style: "currency", currency: "KSH" }).format(value), "Revenue"]}
              />
              <Bar dataKey="total" fill="hsl(var(--chart-2))" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        )}
      </CardContent>
    </Card>
  );
}
